CREATE DATABASE bdmvcproducts;

USE bdmvcproducts;

CREATE TABLE tabla_usuarios (
	USU_ID INT PRIMARY KEY AUTO_INCREMENT,
	USU_UID VARCHAR(100),
	USU_NOMBRES VARCHAR(20) NOT NULL,
	USU_APELLIDOS VARCHAR(20) NOT NULL,
	USU_EMAIL VARCHAR(100) NOT NULL,
	USU_PASSWORD VARCHAR(100) NOT NULL,
	USU_FCH_NAC DATE,
    USU_ROL VARCHAR(10) NOT NULL,
);

CREATE TABLE tabla_productos (
	PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT,
	PRODUCT_UID VARCHAR(100),
	PRODUCT_NAME VARCHAR(20) NOT NULL,
	PRODUCT_CODE VARCHAR(100) NOT NULL
);

CREATE TABLE `tabla_usuarios_productos` (
  `USUPRO_ID` INT(11) NOT NULL,
  `USUPROD_UID` VARCHAR(100) NOT NULL,
  `USUPROD_USU_ID` INT(11) NOT NULL,
  `USUPROD_PROD_ID` INT(11) NOT NULL,
  `USUPROD_INSC_DATE` DATE NOT NULL,
  PRIMARY KEY (`USUPRO_ID`),
  FOREIGN KEY (`USUPROD_USU_ID`) REFERENCES `tabla_usuarios` (`USU_ID`),
  FOREIGN KEY (`USUPROD_PROD_ID`) REFERENCES `tabla_productos` (`PRODUCT_ID`)
) ;